# App information
name: mobileKKM
description: Nieoficjalna aplikacja do obsługi mobilnej wersji KKM na urządzeniach mobilnych.
price: Bezpłatna

# Download buttons
download:
  playstore: https://play.google.com/store/apps/details?id=de.codebucket.mkkm&utm_source=landing-page
  appgallery: https://appgallery.cloud.huawei.com/ag/n/app/C103078099?channelId=landing-page

# Feature list
features:
  - title: Łatwa w obsłudze
    description: Wystarczy raz zalogować się i być zawsze zalogowanym podczas otwierania aplikacji.
    fontawesome_icon_name: hand-sparkles
    
  - title: Zawsze pod ręką
    description: Kontrola biletów? Bez paniki, po prostu otwórz aplikację i pokaż wygenerowany kod biletu.
    fontawesome_icon_name: clipboard-check

  - title: Pomiń kolejkę
    description: Nie trać czasu stojąc w kolejce po nową plastikową kartę lub kupując nowy bilet.
    fontawesome_icon_name: hourglass-end

  - title: Szybko i bezpiecznie
    description: Wybierz swój bilet i zapłać za niego bezpiecznie w aplikacji, bez żadnych kłopotów.
    fontawesome_icon_name: lock

  - title: Nie zapomnij o bilecie
    description: Dowiedz się z wyprzedzeniem o zbliżającym się terminie ważności biletu.
    fontawesome_icon_name: bell

  - title: Synchronizacja online
    description: Bilety są przechowywane online, więc nie musisz się martwić, kiedy zgubisz swój telefon.
    fontawesome_icon_name: sync-alt
